list takes the more memory for stroing a one value 
size (4 bytes)
refrance Count (8 bytes)
object types (8 bytes )
object values (8 bytes)

but numpy array takes only values size (4 bytes )
-->fast to read and less bytes of memory 
--> fixed the types  no need to check the data tyeps of the elements 
--> numpy uses the contigeous memory locations but list is not having the contigeous memory locations 
-->single instuction multiple (SIMD) data  vector processing 
-->effective cache utilization 
--> insertion , deletion, appending , concatenations etc.

Applications of numpys ?
Mathematics (Matlab replacement)
Plotting (matplotlib)
Backed (Pandas,connect 4,Digital photography )
Machine Learning 

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4]) # list to array
print(a)  

[1 2 3 4]


In [9]:
b = np.array([1,12,45,10.0])
print(b)
print(b.dtype)

[ 1. 12. 45. 10.]
float64


In [11]:
#get the dimension
a.ndim

1

In [13]:
# get the shape of array
a.shape

(4,)

In [14]:
# get size
a.itemsize

4

In [15]:
# number of bytes used by the array 
a.nbytes

16

accessing row columns elements 

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# get a specific element in the 2D array
a[0,3]

4

In [21]:
# get the specific row all eleements 
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [22]:
# get the specific columns all elements 
a[:,0]

array([1, 8])

In [27]:
# getting a little more fancy  [startindex:endindex:stepsize]
print(a[0,1:6:2])
print(a[0,1:3:])
print("Odd elements in the first row ")
print(a[0,0:8:2])
print("Even number in the list ")
print(a[0,1:8:2])


[2 4 6]
[2 3]
Odd elements in the first row 
[1 3 5 7]
Even number in the list 
[2 4 6]


In [29]:
# change the element values 
a[1,1] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8 20 10 11 12 13 14]]


In [33]:
# change the specic elements of the values 
a[:,2] = 99  # both row second index number value equals to 11
print(a)

[[ 1  2 99  4  5  6  7]
 [ 8 20 99 11 12 13 14]]


3D examples 

In [37]:
l = []
p = np.arange(1,5).reshape(2,2)
l.append(p)
p = np.arange(5,9).reshape(2,2)
l.append(p)

a = np.array(l)
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
# get the specific elements (work outside in )
a[0,1,1]

4

In [41]:
a[:,1,:] # all elements of the second main subarray 

array([[3, 4],
       [7, 8]])

In [44]:
# replace
a[:,1,:] = [[9,9],[8,8]]
a

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initailze the diffrant types of the arrays

In [47]:
# all 0 arrays
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# all 1 
np.ones((4,3,2))  # (main array row size, row size, col size)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [50]:
# any other numbers
np.full((2,2),22)

array([[22, 22],
       [22, 22]])

In [ ]:
# any other numbers (full likes )

In [52]:
print(a)
np.full_like(a,3)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

In [56]:
# random decimal numbers
print(np.random.rand(4,2)," \n")
print(np.random.rand(1,2,3))

[[0.50209651 0.34080882]
 [0.19661864 0.51748746]
 [0.06297223 0.86334732]
 [0.53851921 0.35206533]]  

[[[0.08747303 0.41757669 0.30411713]
  [0.67588977 0.85945952 0.44238492]]]


In [64]:
t = (1,)
print(t)
# t = tuple(1)
print(type(t))

(1,)
<class 'tuple'>
